title: Peter Palaga
description: Senior sustaining engineer at Red Hat Middleware, WildFly Camel, previously JBoss EAP, Hawkular and others.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
date_format: '%b %-d, %Y'
related_posts_count: 5
url: https://ppalaga.github.io/
baseurl: ""
canonical: https://ppalaga.github.io
github: https://github.com/ppalaga/ppalaga.github.io
production_url: https://ppalaga.github.io

collections:
  category:
    output: true

# GitHub
username: ppalaga
repo: ppalaga.github.io
branch: master

# Jekyll source / destination
source:               .
destination:          _site

plugins:
  - jekyll-regex-replace