title: Peter Palaga
description: Senior sustaining engineer at Red Hat Middleware, WildFly Camel, previously JBoss EAP, Hawkular and others.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
date_format: '%b %-d, %Y'

# GitHub
username: ppalaga
repo: ppalaga.github.io
branch: source

# Jekyll source / destination
source:               .
destination:          _site

plugins:
  - jekyll-regex-replace